<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="EPINHYDW0020" name="Test CaseName :LTI_ENV" tests="15" failures="12" timestamp="24 Aug 2018 08:22:13 GMT" time="0.016" errors="0">
  <testcase name="testaddTwoNumbers" time="0.0" classname="hometask.ten.TestHomeTaskCalculator">
    <failure type="java.lang.IllegalArgumentException" message="argument type mismatch">
      <![CDATA[java.lang.IllegalArgumentException: argument type mismatch
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- testaddTwoNumbers -->
  <testcase name="testaddTwoNumbers" time="0.0" classname="hometask.ten.TestHomeTaskCalculator">
    <failure type="java.lang.AssertionError" message="expected [3.896] but found [3.6870000000000003]">
      <![CDATA[java.lang.AssertionError: expected [3.896] but found [3.6870000000000003]
	at hometask.ten.TestHomeTaskCalculator.testaddTwoNumbers(TestHomeTaskCalculator.java:14)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- testaddTwoNumbers -->
  <testcase name="testaddTwoNumbers" time="0.0" classname="hometask.ten.TestHomeTaskCalculator">
    <failure type="java.lang.IllegalArgumentException" message="argument type mismatch">
      <![CDATA[java.lang.IllegalArgumentException: argument type mismatch
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- testaddTwoNumbers -->
  <testcase name="testdivTwoNumbers" time="0.0" classname="hometask.ten.TestHomeTaskCalculator">
    <failure type="java.lang.IllegalArgumentException" message="argument type mismatch">
      <![CDATA[java.lang.IllegalArgumentException: argument type mismatch
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- testdivTwoNumbers -->
  <testcase name="testdivTwoNumbers" time="0.0" classname="hometask.ten.TestHomeTaskCalculator">
    <failure type="java.lang.AssertionError" message="expected [3.896] but found [0.4945277665180381]">
      <![CDATA[java.lang.AssertionError: expected [3.896] but found [0.4945277665180381]
	at hometask.ten.TestHomeTaskCalculator.testdivTwoNumbers(TestHomeTaskCalculator.java:19)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- testdivTwoNumbers -->
  <testcase name="testdivTwoNumbers" time="0.0" classname="hometask.ten.TestHomeTaskCalculator">
    <failure type="java.lang.IllegalArgumentException" message="argument type mismatch">
      <![CDATA[java.lang.IllegalArgumentException: argument type mismatch
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- testdivTwoNumbers -->
  <testcase name="testMultiNumbers" time="0.0" classname="hometask.ten.TestHomeTaskCalculator">
    <failure type="java.lang.IllegalArgumentException" message="argument type mismatch">
      <![CDATA[java.lang.IllegalArgumentException: argument type mismatch
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- testMultiNumbers -->
  <testcase name="testMultiNumbers" time="0.0" classname="hometask.ten.TestHomeTaskCalculator">
    <failure type="java.lang.AssertionError" message="expected [7.04] but found [7.0]">
      <![CDATA[java.lang.AssertionError: expected [7.04] but found [7.0]
	at hometask.ten.TestHomeTaskCalculator.testMultiNumbers(TestHomeTaskCalculator.java:25)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- testMultiNumbers -->
  <testcase name="testSubtractionNumbers" time="0.0" classname="hometask.ten.TestHomeTaskCalculator">
    <failure type="java.lang.IllegalArgumentException" message="argument type mismatch">
      <![CDATA[java.lang.IllegalArgumentException: argument type mismatch
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- testSubtractionNumbers -->
  <testcase name="testSubtractionNumbers" time="0.0" classname="hometask.ten.TestHomeTaskCalculator">
    <failure type="java.lang.AssertionError" message="expected [1.2] but found [2.16]">
      <![CDATA[java.lang.AssertionError: expected [1.2] but found [2.16]
	at hometask.ten.TestHomeTaskCalculator.testSubtractionNumbers(TestHomeTaskCalculator.java:31)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- testSubtractionNumbers -->
  <testcase name="testSubtractionNumbers" time="0.0" classname="hometask.ten.TestHomeTaskCalculator">
    <failure type="java.lang.IllegalArgumentException" message="argument type mismatch">
      <![CDATA[java.lang.IllegalArgumentException: argument type mismatch
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- testSubtractionNumbers -->
  <testcase name="testisPostive" time="0.0" classname="hometask.ten.TestHomeTaskCalculator"/>
  <testcase name="testSquareRoot" time="0.0" classname="hometask.ten.TestHomeTaskCalculator">
    <failure type="java.lang.IllegalArgumentException" message="argument type mismatch">
      <![CDATA[java.lang.IllegalArgumentException: argument type mismatch
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- testSquareRoot -->
  <testcase name="testisNegative" time="0.0" classname="hometask.ten.TestHomeTaskCalculator"/>
  <testcase name="findAllBugsTest" time="0.0" classname="hometask.ten.TestHomeTaskCalculator"/>
</testsuite> <!-- Test CaseName :LTI_ENV -->
